circumnavigation:
  enabled: false

height-switching:
  enabled: false
  heights:
    world:
      world_nether: -64
      world_the_end: 319
    world_nether:
      world: 255
    world_the_end:
      world: 0

region-switching:
  enabled: false
  regions:
    exampleregion: 'world_the_end'